import React from 'react';
import { INITIAL_MASTERY } from '../../utils/quizData';
import {
  Sparkles,
  Award,
  Flame,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  TrendingUp,
  Brain,
  Cpu,
  Target,
  BookOpen
} from 'lucide-react';

export default function ProgressView({ onNavigateToLab, onNavigateToPractice, onNavigateToLearn }) {
  const masteryData = [
    { name: 'Qubit Basics', score: 90, status: 'Mastered', color: 'emerald', icon: '✓' },
    { name: 'Superposition', score: 70, status: 'Proficient', color: 'indigo', icon: '✓' },
    { name: 'Quantum Gates (X vs H)', score: 50, status: 'Needs Practice', color: 'amber', icon: '◐' },
    { name: 'Measurement & Collapse', score: 80, status: 'Mastered', color: 'emerald', icon: '✓' },
    { name: 'Entanglement (Bell Pairs)', score: 20, status: 'Needs Practice', color: 'purple', icon: '○' }
  ];

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-white p-6 rounded-3xl border border-slate-200/90 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1.5 rounded-xl bg-indigo-50 text-indigo-700">
              <TrendingUp className="w-5 h-5" />
            </span>
            <h2 className="text-xl font-bold text-slate-900">Your Quantum Learning Profile</h2>
          </div>
          <p className="text-xs text-slate-500">
            Real-time mastery index generated by Fullerenes AI across visual labs, circuit synthesis, and quizzes.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="px-3.5 py-2 rounded-2xl bg-indigo-50 border border-indigo-100 text-center">
            <span className="text-[10px] uppercase font-bold text-indigo-600">Overall Progress</span>
            <div className="text-xl font-extrabold text-indigo-900 font-mono">78%</div>
          </div>
          <div className="px-3.5 py-2 rounded-2xl bg-amber-50 border border-amber-100 text-center">
            <span className="text-[10px] uppercase font-bold text-amber-600">Daily Streak</span>
            <div className="text-xl font-extrabold text-amber-900 font-mono">4 Days 🔥</div>
          </div>
        </div>
      </div>

      {/* Grid: Learning Insights & Adaptive Recommendations */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Concept Mastery Bars (7 cols) */}
        <div className="lg:col-span-7 bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/90 shadow-xs space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              Concept Mastery Matrix
            </h3>
            <span className="text-xs text-slate-400 font-medium">Updated live</span>
          </div>

          <div className="space-y-5">
            {masteryData.map(item => (
              <div key={item.name} className="space-y-1.5">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-slate-800 flex items-center gap-1.5">
                    <span className="font-extrabold text-indigo-600">{item.icon}</span>
                    {item.name}
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-slate-100 text-slate-600">
                      {item.status}
                    </span>
                    <span className="font-mono font-bold text-slate-900 w-9 text-right">
                      {item.score}%
                    </span>
                  </div>
                </div>

                <div className="w-full h-2.5 rounded-full bg-slate-100 overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-700 ${
                      item.score >= 80 ? 'bg-emerald-500' : item.score >= 60 ? 'bg-indigo-500' : 'bg-amber-500'
                    }`}
                    style={{ width: `${item.score}%` }}
                  />
                </div>
              </div>
            ))}
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/70 text-xs text-slate-600 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Brain className="w-4 h-4 text-indigo-600" />
              <span>Target for Next Level: Reach 80% on Quantum Gates & Entanglement.</span>
            </div>
            <button
              onClick={() => onNavigateToPractice()}
              className="text-xs font-bold text-indigo-600 hover:text-indigo-800"
            >
              Start Practice →
            </button>
          </div>
        </div>

        {/* Adaptive Learning Insights (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          {/* Personalized Insights Card */}
          <div className="bg-white rounded-3xl p-6 border border-slate-200/90 shadow-xs space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Personalized Learning Insights
            </h3>

            {/* Strong */}
            <div className="p-3.5 rounded-2xl bg-emerald-50/60 border border-emerald-100 space-y-1">
              <div className="text-xs font-bold text-emerald-900 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Strong Mastery Areas:</span>
              </div>
              <ul className="text-xs text-emerald-800 pl-6 list-disc space-y-0.5">
                <li>Qubit Basics & Bloch Coordinates</li>
                <li>Wavefunction Collapse & Born Rule</li>
              </ul>
            </div>

            {/* Needs Practice */}
            <div className="p-3.5 rounded-2xl bg-amber-50/60 border border-amber-100 space-y-1">
              <div className="text-xs font-bold text-amber-900 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-amber-600" />
                <span>Needs Targeted Practice:</span>
              </div>
              <ul className="text-xs text-amber-800 pl-6 list-disc space-y-0.5">
                <li>Distinguishing Pauli-X (NOT) from Hadamard (H)</li>
                <li>Synthesizing 2-qubit Bell Pairs with CNOT</li>
              </ul>
            </div>

            {/* Recommended Next Step */}
            <div className="p-4 rounded-2xl bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-100 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-600 flex items-center gap-1">
                  <Sparkles className="w-3.5 h-3.5" />
                  Recommended Next Step:
                </span>
                <span className="text-[10px] font-bold text-purple-700 bg-purple-100 px-2 py-0.5 rounded-full">
                  Adaptive
                </span>
              </div>
              <h4 className="text-sm font-bold text-indigo-950">
                “Practice: H + CNOT Bell Pair”
              </h4>
              <p className="text-xs text-slate-600 leading-relaxed">
                Connect superposition with controlled entanglement to resolve the correlation gap.
              </p>
              <button
                onClick={() => onNavigateToLab('bell_pair')}
                className="w-full mt-2 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs shadow-xs transition-colors cursor-pointer text-center block"
              >
                Launch Recommended Lab →
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
